#!/bin/bash

export PATH=${PATH}:~/packer/

packer_params=( \
  "-var release=$(git describe --always --tag)" \
  "-var headless=false" \
  "-only=virtualbox" \
  "-var-file=configs/debian-7/minimal.json" \
  "templates/debian-7/template.json"
)

[[ $1 == debian7 || $1 == all ]] && packer build ${packer_params[@]}


packer_params=( \
  "-var release=$(git describe --always --tag)" \
  "-var headless=false" \
  "-only=virtualbox" \
  "-var-file=configs/debian-8/minimal.json" \
  "templates/debian-8/template.json"
)

[[ $1 == debian8 || $1 == all ]] && packer build ${packer_params[@]}


packer_params=( \
  "-var release=$(git describe --always --tag)" \
  "-var headless=false" \
  "-only=virtualbox" \
  "-var-file=configs/centos-6/minimal.json" \
  "templates/centos-6/template.json"
)

[[ $1 == centos6 || $1 == all ]] && packer build ${packer_params[@]}


packer_params=( \
  "-var release=$(git describe --always --tag)" \
  "-var headless=false" \
  "-only=virtualbox" \
  "-var-file=configs/centos-7/minimal.json" \
  "templates/centos-7/template.json"
)

[[ $1 == centos7 || $1 == all ]] && packer build ${packer_params[@]}
